// ─────────────────────────────────────────────────────────────────────────────
// triagem-utils.js — Condutas clínicas e helpers para triagem QT
// Extraído de App.jsx — sem dependências externas
// ─────────────────────────────────────────────────────────────────────────────

export const CONDUTA_REFS_ONCO=[
  {rotulo:"CDC - febre durante quimioterapia",url:"https://www.cdc.gov/cancer/preventinfections/symptoms.htm"},
  {rotulo:"ASCO/IDSA - neutropenia febril em adultos com câncer",url:"https://ascopubs.org/doi/10.1200/JCO.2017.77.6211"},
  {rotulo:"ESMO - diarreia em pacientes oncológicos",url:"https://www.esmo.org/guidelines/guidelines-by-topic/supportive-and-palliative-care/diarrhoea-in-adult-cancer-patients"},
  {rotulo:"IDSA/SHEA 2021 - Clostridioides difficile",url:"https://www.idsociety.org/practice-guideline/clostridioides-difficile-2021-focused-update/"},
  {rotulo:"MASCC/ISOO 2020 - mucosite",url:"https://pubmed.ncbi.nlm.nih.gov/32205390/"},
  {rotulo:"NCI - plaquetas baixas e sangramento",url:"https://www.cancer.gov/about-cancer/treatment/side-effects/bleeding-bruising"}
];

export const CONDUTAS_TRIAGEM_ONCO={
  febre:{id:"febre",titulo:"Febre >= 38 C",gravidade:"Emergencia oncologica",nivel:"critico",acionar:"Acionar médico imediatamente. Nao liberar QT ate avaliacao.",acao:"Aferir sinais vitais, confirmar temperatura, avaliar calafrios, queda do estado geral e acesso venoso. Manter paciente em observacao e comunicar risco de neutropenia febril.",exames:["Hemograma com diferencial e neutrofilos","PCR e lactato se instavel","Hemoculturas antes de antimicrobiano quando possivel","Urocultura e RX/TC conforme foco"],resumo:"Febre em paciente em quimioterapia deve ser tratada como emergencia ate excluir neutropenia febril ou sepse.",prescricao:"MODELO EDITAVEL - REQUER VALIDACAO MEDICA\n\nPaciente com febre em tratamento oncologico.\n\n1. Encaminhar para avaliacao medica imediata / emergencia oncologica.\n2. Checar sinais vitais seriados, acesso venoso, alergias e uso recente de antibioticos.\n3. Solicitar hemograma com diferencial, funcao renal/hepatica, PCR, culturas conforme foco e imagem se indicado.\n4. Considerar protocolo institucional de neutropenia febril/sepses apos coleta de culturas, sem atrasar conduta quando instavel.\n5. Suspender quimioterapia ate liberacao medica.",refs:[0,1]},
  calafrios:{id:"calafrios",titulo:"Febre com calafrios intensos",gravidade:"Emergencia infecciosa",nivel:"critico",acionar:"Acionar médico imediatamente. Priorizar avaliacao de bacteremia/sepse.",acao:"Isolar prioridade alta, aferir PA/FC/FR/SpO2/temperatura, avaliar perfusao, tremores, hipotensao e acesso venoso central.",exames:["Hemoculturas perifericas e do cateter se houver","Hemograma com diferencial","Lactato se instabilidade","Funcao renal/hepatica"],resumo:"Calafrios intensos sugerem bacteremia em paciente imunossuprimido e exigem fluxo rapido com medico.",prescricao:"MODELO EDITAVEL - REQUER VALIDACAO MEDICA\n\n1. Atendimento medico imediato por suspeita de bacteremia/sepse.\n2. Coletar culturas conforme protocolo institucional, incluindo cateter se presente.\n3. Iniciar pacote de sepse se instabilidade clinica.\n4. Considerar antimicrobiano empirico conforme protocolo local, alergias e funcao renal.\n5. Reavaliar liberacao de QT somente apos definicao medica.",refs:[0,1]},
  cateter:{id:"cateter",titulo:"Cateter com hiperemia, dor ou secrecao",gravidade:"Alto risco",nivel:"alto",acionar:"Acionar médico no mesmo atendimento. Avaliar infeccao de corrente sanguinea relacionada a cateter.",acao:"Inspecionar cateter, registrar foto se permitido, nao manipular desnecessariamente, aferir temperatura e pesquisar dor, secrecao, rubor, edema.",exames:["Hemograma","PCR","Culturas se febre ou secrecao","Cultura de secrecao se disponivel"],resumo:"Sinais inflamatórios em cateter durante QT podem indicar infeccao local ou sistemica.",prescricao:"MODELO EDITAVEL - REQUER VALIDACAO MEDICA\n\n1. Avaliacao medica do cateter e risco de infeccao sistemica.\n2. Coletar exames/culturas conforme achados e protocolo institucional.\n3. Definir manutencao, bloqueio, retirada ou antimicrobiano conforme avaliacao medica.\n4. Evitar usar o cateter para QT ate liberacao.",refs:[1]},
  tosse:{id:"tosse",titulo:"Tosse com catarro purulento",gravidade:"Alto risco",nivel:"alto",acionar:"Acionar médico, especialmente se febre, dispneia, SpO2 baixa ou neutropenia.",acao:"Aferir SpO2, FR, temperatura, ausculta se rotina local permitir, checar inicio dos sintomas e contato infeccioso.",exames:["Hemograma com diferencial","PCR","Radiografia de torax ou TC conforme avaliacao","Cultura/viral conforme protocolo"],resumo:"Quadro respiratorio purulento em paciente oncológico pode evoluir rapidamente se houver neutropenia.",prescricao:"MODELO EDITAVEL - REQUER VALIDACAO MEDICA\n\n1. Avaliacao medica para infeccao respiratoria/pneumonia.\n2. Solicitar imagem de torax e exames laboratoriais conforme gravidade.\n3. Considerar antimicrobiano conforme protocolo, alergias, funcao renal e epidemiologia local.\n4. Suspender QT se infeccao ativa ou criterios clinicos nao seguros.",refs:[0,1]},
  urina:{id:"urina",titulo:"Disuria ou urina fetida",gravidade:"Atencao",nivel:"moderado",acionar:"Acionar médico se febre, dor lombar, calafrios, neutropenia ou queda do estado geral.",acao:"Checar febre, dor lombar, urgencia urinaria, hematúria, ingesta e sinais de desidratacao.",exames:["EAS","Urocultura antes de antibiotico quando possivel","Hemograma se febre ou QT recente","Funcao renal se necessario"],resumo:"Sintomas urinarios em QT podem indicar ITU simples ou foco de sepse quando associados a febre/neutropenia.",prescricao:"MODELO EDITAVEL - REQUER VALIDACAO MEDICA\n\n1. Avaliacao medica para ITU e risco de infeccao complicada.\n2. Solicitar EAS/urocultura antes de antimicrobiano quando possivel.\n3. Definir tratamento conforme gravidade, alergias, funcao renal e culturas previas.\n4. Orientar retorno imediato se febre, calafrios, dor lombar ou piora.",refs:[0,1]},
  escara:{id:"escara",titulo:"Escara, ferida infectada ou celulite",gravidade:"Atencao alta",nivel:"alto",acionar:"Acionar médico no mesmo dia; imediato se febre, dor intensa, necrose ou neutropenia.",acao:"Avaliar extensao, dor, calor, edema, secrecao, odor e sinais sistemicos. Marcar bordas se celulite e registrar aspecto.",exames:["Hemograma","PCR","Cultura se secrecao","Imagem se suspeita de abscesso ou infeccao profunda"],resumo:"Ferida/celulite em paciente oncológico pode ser porta de entrada para infeccao sistemica.",prescricao:"MODELO EDITAVEL - REQUER VALIDACAO MEDICA\n\n1. Avaliacao medica da lesao e necessidade de curativo, drenagem ou antimicrobiano.\n2. Coletar exames e cultura se secrecao.\n3. Definir cobertura e encaminhamento conforme extensao, neutropenia e sinais sistemicos.\n4. Reavaliar antes de liberar QT.",refs:[1]},
  faringite:{id:"faringite",titulo:"Faringite e odinofagia intensa",gravidade:"Atencao",nivel:"moderado",acionar:"Acionar médico se disfagia importante, febre, desidratacao, neutropenia ou suspeita de mucosite grave.",acao:"Avaliar ingesta, dor, placas, sangramento oral, sinais de mucosite, perda de peso e hidratacao.",exames:["Hemograma se QT recente","Avaliar cultura/testes conforme protocolo","Funcao renal se desidratacao"],resumo:"Odinofagia intensa pode representar infeccao, mucosite ou toxicidade que impede alimentacao/hidratacao.",prescricao:"MODELO EDITAVEL - REQUER VALIDACAO MEDICA\n\n1. Avaliacao medica de cavidade oral/orofaringe e hidratacao.\n2. Considerar analgesia, hidratacao, cuidados orais e investigacao infecciosa conforme exame.\n3. Definir necessidade de antifungico/antiviral/antibiotico conforme suspeita e protocolo.\n4. Adiar QT se toxicidade relevante ou infeccao ativa.",refs:[4]},
  disenteria:{id:"disenteria",titulo:"Diarreia com colica e odor fetido",gravidade:"Alto risco",nivel:"alto",acionar:"Acionar médico no mesmo atendimento; emergencia se febre, sangue, desidratacao, dor intensa ou neutropenia.",acao:"Quantificar evacuacoes, avaliar hidratacao, dor, sangue, uso recente de antibiotico/internacao e sinais vitais.",exames:["Hemograma e eletrólitos","Funcao renal","Pesquisa/toxina/PCR para C. difficile se risco","Coprocultura conforme contexto"],resumo:"Diarreia fétida com cólica em oncologia sugere infeccao, C. difficile ou toxicidade, com risco de desidratacao e sepse.",prescricao:"MODELO EDITAVEL - REQUER VALIDACAO MEDICA\n\n1. Avaliacao medica para diarreia infecciosa/toxicidade e risco de internacao.\n2. Solicitar eletrólitos, funcao renal e investigacao de C. difficile quando indicado.\n3. Hidratar conforme gravidade e corrigir disturbios eletroliticos.\n4. Evitar antidiarreico ate excluir infeccao invasiva/C. difficile quando houver sinais de alerta.\n5. Suspender QT ate estabilizacao e decisao medica.",refs:[2,3]},
  mucosite:{id:"mucosite",titulo:"Mucosite intensa G3/G4",gravidade:"Alto risco",nivel:"alto",acionar:"Acionar médico. Avaliar desidratacao, infeccao, dor intensa e necessidade de suporte.",acao:"Avaliar capacidade de ingerir liquidos/alimentos, dor, sangramento, placas, febre, perda ponderal e hidratacao.",exames:["Hemograma com neutrofilos","Funcao renal se baixa ingesta","Culturas se febre","Avaliar eletrólitos se desidratacao"],resumo:"Mucosite G3/G4 impede alimentação ou hidratação adequada e pode exigir analgesia, suporte e adiamento de QT.",prescricao:"MODELO EDITAVEL - REQUER VALIDACAO MEDICA\n\n1. Avaliacao medica de mucosite grave e hidratacao.\n2. Considerar analgesia escalonada, cuidados orais, hidratacao EV e suporte nutricional conforme gravidade.\n3. Investigar infeccao secundaria se febre/placas/neutropenia.\n4. Adiar QT e reavaliar dose/protocolo conforme toxicidade.",refs:[4]},
  sangramento:{id:"sangramento",titulo:"Sangramento ativo",gravidade:"Emergencia",nivel:"critico",acionar:"Acionar médico imediatamente. Avaliar sangramento maior e trombocitopenia.",acao:"Identificar local, volume, estabilidade hemodinamica, uso de anticoagulante/antiagregante e sinais de choque.",exames:["Hemograma com plaquetas","Coagulograma","Funcao renal/hepatica","Tipagem/prova cruzada se sangramento importante"],resumo:"Sangramento ativo em paciente em QT pode indicar trombocitopenia, coagulopatia ou lesao tumoral e requer avaliação urgente.",prescricao:"MODELO EDITAVEL - REQUER VALIDACAO MEDICA\n\n1. Avaliacao medica imediata e monitorizacao.\n2. Solicitar hemograma/plaquetas, coagulograma e exames conforme sitio.\n3. Definir necessidade de hemoderivados, reversao de anticoagulantes ou procedimento conforme protocolo.\n4. Suspender QT e anticoagulantes apenas por decisao medica.",refs:[5]},
  dispneia:{id:"dispneia",titulo:"Falta de ar em repouso ou SpO2 baixa",gravidade:"Emergencia",nivel:"critico",acionar:"Acionar médico imediatamente. Priorizar sala de emergencia se SpO2 baixa ou desconforto respiratorio.",acao:"Aferir SpO2, FR, PA, FC, nivel de consciencia e dor toracica. Posicionar paciente e seguir protocolo institucional de oxigenoterapia se autorizado.",exames:["Oximetria seriada","Hemograma","Gasometria se grave","RX/TC torax conforme suspeita","ECG se dor/risco cardiovascular"],resumo:"Dispneia em repouso em oncologia pode indicar infeccao, embolia pulmonar, derrame pleural, anemia grave ou toxicidade.",prescricao:"MODELO EDITAVEL - REQUER VALIDACAO MEDICA\n\n1. Avaliacao medica imediata por dispneia em repouso/hipoxemia.\n2. Monitorar sinais vitais e SpO2; oxigenoterapia conforme protocolo institucional.\n3. Solicitar imagem toracica e exames guiados por suspeita clinica.\n4. Considerar embolia pulmonar, pneumonia, derrame pleural, anemia e toxicidade medicamentosa.\n5. Nao liberar QT ate estabilizacao.",refs:[0,1]},
  confusao:{id:"confusao",titulo:"Confusao mental ou desorientacao",gravidade:"Emergencia",nivel:"critico",acionar:"Acionar médico imediatamente. Avaliar sepse, hipoxemia, disturbio metabolico e evento neurologico.",acao:"Checar glicemia capilar se protocolo permitir, sinais vitais, SpO2, febre, medicacoes recentes, queda/trauma e nivel de consciencia.",exames:["Glicemia capilar","Hemograma","Eletrólitos, calcio, funcao renal/hepatica","Culturas se febre","Imagem neurologica conforme avaliacao"],resumo:"Confusão mental nova em paciente oncológico é sinal de risco e exige avaliação imediata.",prescricao:"MODELO EDITAVEL - REQUER VALIDACAO MEDICA\n\n1. Avaliacao medica imediata por alteracao do sensório.\n2. Monitorizar sinais vitais, glicemia e SpO2.\n3. Investigar causas infecciosas, metabolicas, hipoxemia, medicamentos e evento neurologico.\n4. Encaminhar para emergencia se inicio agudo, febre, déficit focal, hipoxemia ou instabilidade.",refs:[0,1]}
};

export const CONDUTA_ALIASES=[
  ["febre",/febre\s*(?:>=|≥|maior|38)/i],
  ["calafrios",/calafrios|bacteremia/i],
  ["cateter",/cateter|hiperemia|secre[cç][aã]o no cateter/i],
  ["tosse",/tosse|catarro|pneumonia/i],
  ["urina",/urina|dis[uú]ria|itu/i],
  ["escara",/escara|celulite|ferida/i],
  ["faringite",/faringite|odinofagia|engolir/i],
  ["disenteria",/diarreia|c\.?\s*difficile|odor f[eé]tido/i],
  ["mucosite",/mucosite/i],
  ["sangramento",/sangramento/i],
  ["dispneia",/falta de ar|dispneia|spo2|spo₂/i],
  ["confusao",/confus[aã]o|desorient/i]
];

export function condutaTriagemPorId(id){return CONDUTAS_TRIAGEM_ONCO[id]||null;}

export function condutasDeResumoTriagem(resumo="",ids=[]){
  const set=new Set((ids||[]).filter(Boolean));
  CONDUTA_ALIASES.forEach(([id,rx])=>{if(rx.test(resumo))set.add(id);});
  return [...set].map(condutaTriagemPorId).filter(Boolean);
}

export function textoPrescricaoTriagem(condutas=[]){
  if(!condutas.length)return "Sem prescrição-modelo vinculada aos sinais selecionados.";
  return condutas.map(c=>`${c.titulo}\n${c.prescricao}`).join("\n\n"+"=".repeat(52)+"\n\n");
}

export function refsCondutas(condutas=[]){
  const ids=[...new Set(condutas.flatMap(c=>c.refs||[]))];
  return ids.map(i=>CONDUTA_REFS_ONCO[i]).filter(Boolean);
}
